// Precomputes the land dots of studio-map (run once; output committed): an equirectangular grid
// over the 1920×1080 frame, kept where the point is on land (world-atlas 110m, ISC).
//   node make-dots.mjs
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { geoContains } from 'd3-geo';
import { feature } from 'topojson-client';

const require = createRequire(import.meta.url);
const world = require('world-atlas/land-110m.json');
const land = feature(world, world.objects.land);

// Must match studio-map.html: x = (lon + 180) / 360 * 1920, y = TOP + (84 - lat) * K.
const K = 1920 / 360;
const TOP = (1080 - 142 * K) / 2;
const STEP = 11;
const dots = [];
for (let y = TOP + STEP / 2; y < TOP + 142 * K; y += STEP) {
  for (let x = STEP / 2; x < 1920; x += STEP) {
    const lon = (x / 1920) * 360 - 180;
    const lat = 84 - (y - TOP) / K;
    if (geoContains(land, [lon, lat])) dots.push(Math.round(x), Math.round(y));
  }
}
writeFileSync(new URL('./dots.js', import.meta.url), `// Generated by make-dots.mjs (world-atlas land-110m, ISC). Flat [x, y, x, y, ...] in frame pixels.\nwindow.STUDIO_DOTS = ${JSON.stringify(dots)};\n`);
console.log(`${dots.length / 2} dots`);
