/**
 * HyperFrames catalog (heygen-com/hyperframes, Apache-2.0): 165 blocks and 223
 * components rendered by the Remotion package through the HyperFrames runtime.
 *
 * The engine stays catalog-agnostic: it carries a `HyperFramesUse` into a
 * graphic layer of kind `hyperframes`, validates it against a catalog when one
 * is given, and builds the page URL the renderer loads. The catalog JSON is
 * generated by `packages/remotion/scripts/hyperframes-sync.mjs` and committed
 * as `packages/engine/hyperframes-catalog.json`.
 */
import type { JsonObject, JsonValue } from '../model/primitives.js';

export type HyperFramesItemType = 'block' | 'component';

export interface HyperFramesVariable {
  id: string;
  type: 'string' | 'number' | 'boolean' | 'color' | 'enum' | 'image' | 'array' | string;
  role?: string;
  label?: string;
  description?: string;
  default?: JsonValue;
  options?: JsonValue[];
}

export interface HyperFramesItem {
  name: string;
  type: HyperFramesItemType;
  title: string;
  description: string;
  tags: string[];
  family?: string;
  jobs?: string[];
  dimensions: { width: number; height: number };
  /** Seconds. */
  duration: number;
  /** Components without their own duration: they last as long as the host gives them. */
  elasticDuration?: boolean;
  /** Page path relative to the renderer's public root. */
  path: string;
  /** `page`: a standalone page; `host`: a <template> snippet mounted by hyperframes/host.html. */
  mount: 'page' | 'host';
  /** Root composition id when it differs from the name. */
  compositionId?: string;
  demo?: string;
  variables: HyperFramesVariable[];
  params: JsonValue[];
  /** Images, 3D models, audio shipped inside the item: rights to verify (bible SRC-01). */
  embeddedMedia: string[];
  /** Files the registry lists but the repository does not ship: the item renders with holes. */
  missingFiles?: string[];
  /** Why the item does not render in headless Chromium (probe), e.g. WebGPU only. */
  unsupported?: string;
  /** `studio`: our own blocks (packages/remotion/hyperframes-studio); absent: the HyperFrames registry. */
  source?: 'studio';
  dependencies: string[];
  preview?: string;
}

export interface HyperFramesCatalog {
  source: string;
  commit: string;
  runtime: string;
  license: string;
  fonts: string[];
  items: HyperFramesItem[];
}

/** One use of a catalog item in a shot: full-frame block or overlay. */
export interface HyperFramesUse {
  /** Catalog item name, e.g. "bar-chart-race", "lt-clean-bar", "count-up". */
  item: string;
  /** Filled from the catalog when omitted (default `block`). */
  type?: HyperFramesItemType;
  /** Values for the item's declared variables. */
  variables?: JsonObject;
  /** Seconds into the item's own timeline at the layer's first frame (default 0). */
  startAt?: number;
  /** Playback rate of the item's timeline (default 1). */
  speed?: number;
  /** Components: mount box in percent of the frame [x, y, width, height] (default full frame). */
  box?: [number, number, number, number];
  /** Components: design tokens (`--bg`, `--fg`, `--brand`, `--accent`, `--font-display`…). */
  theme?: Record<string, string>;
  /** Components: host background (default transparent). */
  background?: string;
  /** Overlays: first frame inside the shot (default 0). */
  startFrame?: number;
  /** Overlays: length in frames (default: to the end of the shot). */
  durationInFrames?: number;
}

export interface HyperFramesIssue {
  path: string;
  code: string;
  message: string;
  severity: 'error' | 'warning';
}

export function findHyperFramesItem(catalog: HyperFramesCatalog | undefined, name: string): HyperFramesItem | undefined {
  return catalog?.items.find((i) => i.name === name);
}

const isObj = (v: unknown): v is Record<string, unknown> => typeof v === 'object' && v !== null && !Array.isArray(v);
const isNum = (v: unknown): v is number => typeof v === 'number' && Number.isFinite(v);

function variableMatches(v: HyperFramesVariable, value: unknown): boolean {
  switch (v.type) {
    case 'number': return isNum(value);
    case 'boolean': return typeof value === 'boolean';
    case 'string':
    case 'color':
    case 'image': return typeof value === 'string';
    case 'enum': return !v.options?.length || v.options.includes(value as JsonValue);
    default: return true;
  }
}

/** Structural checks, plus catalog checks (item exists, variables declared and typed) when a catalog is given. */
export function checkHyperFramesUse(use: unknown, path: string, catalog?: HyperFramesCatalog): HyperFramesIssue[] {
  const issues: HyperFramesIssue[] = [];
  const err = (p: string, code: string, message: string) => issues.push({ path: p, code, message, severity: 'error' });
  const warn = (p: string, code: string, message: string) => issues.push({ path: p, code, message, severity: 'warning' });
  if (!isObj(use) || typeof use.item !== 'string' || use.item === '') {
    err(path, 'hyperframes.item', 'a HyperFrames use needs an item name');
    return issues;
  }
  if (use.type !== undefined && use.type !== 'block' && use.type !== 'component') err(`${path}.type`, 'hyperframes.type', 'type must be block or component');
  if (use.variables !== undefined && !isObj(use.variables)) err(`${path}.variables`, 'hyperframes.variables', 'variables must be an object');
  if (use.startAt !== undefined && !(isNum(use.startAt) && use.startAt >= 0)) err(`${path}.startAt`, 'hyperframes.startAt', 'startAt must be ≥ 0 seconds');
  if (use.speed !== undefined && !(isNum(use.speed) && use.speed > 0)) err(`${path}.speed`, 'hyperframes.speed', 'speed must be > 0');
  if (use.box !== undefined && !(Array.isArray(use.box) && use.box.length === 4 && use.box.every((n) => isNum(n) && n >= 0 && n <= 100))) {
    err(`${path}.box`, 'hyperframes.box', 'box must be [x, y, width, height] in percent (0..100)');
  }
  if (use.theme !== undefined && !(isObj(use.theme) && Object.values(use.theme).every((v) => typeof v === 'string'))) err(`${path}.theme`, 'hyperframes.theme', 'theme must map token names to strings');
  if (use.startFrame !== undefined && !(Number.isInteger(use.startFrame) && (use.startFrame as number) >= 0)) err(`${path}.startFrame`, 'hyperframes.startFrame', 'startFrame must be an integer ≥ 0');
  if (use.durationInFrames !== undefined && !(Number.isInteger(use.durationInFrames) && (use.durationInFrames as number) > 0)) err(`${path}.durationInFrames`, 'hyperframes.duration', 'durationInFrames must be a positive integer');
  if (!catalog) return issues;
  const item = findHyperFramesItem(catalog, use.item);
  if (!item) {
    err(`${path}.item`, 'hyperframes.unknown', `"${use.item}" is not in the HyperFrames catalog (${catalog.commit})`);
    return issues;
  }
  if (item.unsupported) err(`${path}.item`, 'hyperframes.unsupported', `"${item.name}" does not render in headless Chromium: ${item.unsupported}`);
  if (item.missingFiles?.length) warn(`${path}.item`, 'hyperframes.missingFiles', `"${item.name}" misses ${item.missingFiles.length} file(s) the registry does not ship (${item.missingFiles[0]}…): replace them through its variables`);
  if (use.type !== undefined && use.type !== item.type) err(`${path}.type`, 'hyperframes.type', `"${item.name}" is a ${item.type}`);
  if (isObj(use.variables)) {
    for (const [k, value] of Object.entries(use.variables)) {
      const v = item.variables.find((x) => x.id === k);
      if (!v) warn(`${path}.variables.${k}`, 'hyperframes.variable.unknown', `"${item.name}" declares no variable "${k}"; it will be ignored`);
      else if (!variableMatches(v, value)) err(`${path}.variables.${k}`, 'hyperframes.variable.type', `"${k}" expects ${v.type}${v.options?.length ? ` (${v.options.join(', ')})` : ''}`);
    }
  }
  if (item.type === 'block' && item.variables.length === 0 && use.variables && Object.keys(use.variables).length) {
    warn(`${path}.variables`, 'hyperframes.fixedContent', `"${item.name}" has fixed content (no variables); what it shows cannot be changed`);
  }
  return issues;
}

/**
 * Graphic-layer data for a use, completed from the catalog when available.
 * `layerSeconds` is the layer's length: elastic components are stretched to it.
 */
export function hyperframesLayerData(use: HyperFramesUse, catalog?: HyperFramesCatalog, layerSeconds?: number): JsonObject {
  const item = findHyperFramesItem(catalog, use.item);
  const type = use.type ?? item?.type ?? 'block';
  const data: JsonObject = { item: use.item, itemType: type };
  // The catalog revision is part of the data, so a re-sync invalidates cached renders.
  if (catalog) data.rev = catalog.commit;
  if (item) data.duration = item.elasticDuration && layerSeconds ? layerSeconds : item.duration;
  // Snippet path, unless it is the component default (components/<name>/<name>.html).
  if (item?.mount === 'host' && (type === 'block' || item.compositionId)) data.src = item.path.replace(/^hyperframes\//, '');
  if (item?.compositionId) data.compositionId = item.compositionId;
  const variables: JsonObject = { ...use.variables };
  // Elastic page blocks (studio blocks) read their length from a `duration` variable: the part of
  // their timeline this layer plays, from `startAt`.
  if (item?.elasticDuration && item.mount === 'page' && layerSeconds && variables.duration === undefined) {
    variables.duration = Math.round(((use.startAt ?? 0) + layerSeconds * (use.speed ?? 1)) * 1000) / 1000;
    data.duration = variables.duration;
  }
  if (Object.keys(variables).length) data.variables = variables;
  if (use.startAt) data.startAt = use.startAt;
  if (use.speed !== undefined && use.speed !== 1) data.speed = use.speed;
  // Box, tokens and background apply to snippets mounted by host.html only.
  const hosted = type === 'component' || item?.mount === 'host';
  if (hosted && use.box) data.box = [...use.box];
  if (hosted && use.theme) data.theme = { ...use.theme };
  if (hosted && use.background) data.background = use.background;
  return data;
}

/**
 * Page URL relative to the renderer's public root. Blocks load their own page
 * (`?hfv=` variables, read by the injected bridge); components and snippet
 * blocks are mounted in `hyperframes/host.html` like the catalog's demo pages.
 */
export function hyperframesPageUrl(data: JsonObject): string {
  const name = String(data.item);
  const variables = isObj(data.variables) ? data.variables : {};
  if (data.itemType === 'component' || typeof data.src === 'string') {
    const q = new URLSearchParams({ c: typeof data.compositionId === 'string' ? data.compositionId : name, v: JSON.stringify(variables) });
    if (typeof data.src === 'string') q.set('src', data.src);
    if (isNum(data.duration)) q.set('d', String(data.duration));
    if (Array.isArray(data.box)) q.set('box', data.box.join(','));
    if (isObj(data.theme)) q.set('theme', JSON.stringify(data.theme));
    if (typeof data.background === 'string') q.set('bg', data.background);
    return `hyperframes/host.html?${q.toString()}`;
  }
  const q = Object.keys(variables).length ? `?hfv=${encodeURIComponent(JSON.stringify(variables))}` : '';
  return `hyperframes/blocks/${name}/${name}.html${q}`;
}

/** Item time (seconds) at a layer-local frame: startAt + t·speed, held on the last frame. */
export function hyperframesTimeAt(data: JsonObject, frame: number, fps: number): number {
  const t = (isNum(data.startAt) ? data.startAt : 0) + (frame / fps) * (isNum(data.speed) ? data.speed : 1);
  return isNum(data.duration) && data.duration > 0 ? Math.min(t, Math.max(0, data.duration - 1 / fps)) : t;
}
